### ISSUE TITLE
Improve the file structure of the plugins

### ISSUE THREAD

**Issue by kylef** [CocoaPods/cocoapods-plugin-template#8]
The current structure is a big cumbersome and sometimes it's not clear where things belong. I propose the following layout, where `pluginname` is the plugin name, for example `cocoapods-trunk`.

```
.
├── lib
│   ├── cocoapods_plugin.rb
│   ├── cocoapods-plugin_name.rb
│   └── cocoapods-plugin_name
│       ├── command
│       │   └── command_name.rb
│       ├── command.rb
│       └── gem_version.rb
└── cocoapods-plugin_name.gemspec

3 directories, 5 files
```
#### cocoapods_plugin.rb

This is the main point the plugin is invoked, it will require the `cocoapods-plugin_name` file and it will allow you to register and plugin hooks.

/cc @alloy

**Comment by alloy** [comment]
What is `command.rb` for?

**Comment by kylef** [comment]
It's for requiring the specific command files
